import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

export const generateIncidentReport = (alert) => {
  const doc = jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // 🏛️ HEADER: OFFICIAL GOVERNMENT STYLE
  doc.setFillColor(31, 41, 55); // Dark gray
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('SAFECITY OPERATIONS NETWORK', 20, 20);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('OFFICIAL INCIDENT REPORT - CLASSIFIED DOCUMENT', 20, 30);
  doc.text(`REPORT ID: ${alert._id.toUpperCase()}`, pageWidth - 20, 30, { align: 'right' });

  // 📑 SECTION 1: INCIDENT OVERVIEW
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('1. INCIDENT OVERVIEW', 20, 55);
  doc.line(20, 57, 80, 57);

  const overviewData = [
    ['Incident Type', alert.type.toUpperCase()],
    ['Priority Level', alert.priority || 'MEDIUM'],
    ['Current Status', alert.status.toUpperCase()],
    ['Assigned Dept', (alert.assignedDepartment || 'NONE').toUpperCase()],
    ['City/State', `${alert.city || 'N/A'}, ${alert.state || 'N/A'}`],
    ['GPS Coordinates', `${alert.location.lat.toFixed(4)}, ${alert.location.lng.toFixed(4)}`]
  ];

  doc.autoTable({
    startY: 65,
    head: [['Field', 'Data']],
    body: overviewData,
    theme: 'striped',
    headStyles: { fillColor: [220, 38, 38] }, // Red header
    margin: { left: 20, right: 20 }
  });

  // 👤 SECTION 2: REPORTER DETAILS
  const finalY = doc.lastAutoTable.finalY + 15;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('2. REPORTER INFORMATION', 20, finalY);
  doc.line(20, finalY + 2, 85, finalY + 2);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`Name: ${alert.reporterName}`, 20, finalY + 12);
  doc.text(`Contact: ${alert.reporterPhone}`, 20, finalY + 20);
  doc.text(`Description: ${alert.description || 'No description provided.'}`, 20, finalY + 28, { maxWidth: 170 });

  // ⏱️ SECTION 3: CHRONOS TIMELINE (AUDIT TRAIL)
  const timelineY = finalY + 45;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('3. RESPONSE TIMELINE (AUDIT TRAIL)', 20, timelineY);
  doc.line(20, timelineY + 2, 105, timelineY + 2);

  const timelineData = (alert.timeline || []).map(event => [
    new Date(event.timestamp).toLocaleString(),
    event.status,
    event.message
  ]);

  doc.autoTable({
    startY: timelineY + 10,
    head: [['Timestamp', 'Status', 'Event Log']],
    body: timelineData,
    theme: 'grid',
    headStyles: { fillColor: [31, 41, 55] },
    margin: { left: 20, right: 20 }
  });

  // 🛡️ FOOTER: LEGAL DISCLAIMER
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('This document is generated by the SafeCity AI Core. It serves as an official record of the emergency response sequence.', 20, pageHeight - 20);
  doc.text('© 2026 SafeCity Operations Network. All Rights Reserved.', 20, pageHeight - 15);
  doc.text('CONFIDENTIAL - AUTHORIZED ACCESS ONLY', pageWidth / 2, pageHeight - 15, { align: 'center' });

  // SAVE THE PDF
  doc.save(`SafeCity_Report_${alert._id.slice(-6).toUpperCase()}.pdf`);
};
